In [1]:
import os


os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n')  # 列名
    f.write('NA, Pave, 127500\n')  # 每行表示一个数据样本
    f.write('2, Na, 106000\n')
    f.write('4, Na, 178100\n')
    f.write('NA, Na, 140000\n')

In [2]:
import pandas as pd


data = pd.read_csv(data_file)
data

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0     Na  106000
2       4.0     Na  178100
3       NaN     Na  140000

## 处理缺失值

注意，“NaN”项代表缺失值。
**为了处理缺失的数据，典型的方法包括*插值法*和*删除法*，**
其中插值法用一个替代值弥补缺失值，而删除法则直接忽略缺失值。
在(**这里，我们将考虑插值法**)。

通过位置索引`iloc`，我们将`data`分成`inputs`和`outputs`，
其中前者为`data`的前两列，而后者为`data`的最后一列。
对于`inputs`中缺少的数值，我们用同一列的均值替换“NaN”项。

In [3]:
inputs, outputs = data.iloc[:, 0: 2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
inputs

   NumRooms  Alley
0       3.0   Pave
1       2.0     Na
2       4.0     Na
3       3.0     Na

**对于`inputs`中的类别值或离散值，我们将“NaN”视为一个类别。**

由于“巷子类型”（“Alley”）列只接受两种类型的类别值“Pave”和“NaN”，
`pandas`可以自动将此列转换为两列“Alley_Pave”和“Alley_nan”。
巷子类型为“Pave”的行会将“Alley_Pave”的值设置为1，“Alley_nan”的值设置为0。
缺少巷子类型的行会将“Alley_Pave”和“Alley_nan”分别设置为0和1。

In [4]:
inputs = pd.get_dummies(inputs, dummy_na=False)
inputs

   NumRooms   Alley_ Na   Alley_ Pave
0       3.0           0             1
1       2.0           1             0
2       4.0           1             0
3       3.0           1             0

In [5]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 0., 1.],
         [2., 1., 0.],
         [4., 1., 0.],
         [3., 1., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))